export const siteConfig = {
  name: "Jay Consejo",
  logo: "JDC",
  jobTitle: "AI, Web & Systems Builder",
  title: "Jay Consejo — AI, Web Apps & Systems Builder",
  description:
    "Jay Consejo — ships internal tools, finance & ops systems, and AI products in weeks, not quarters. 2 client systems in production, 6 products shipped. Manila-based, works globally.",
  url: "https://jayconsejo.com",
  /** Single source for every headline number on the site. */
  stats: {
    clientSystems: 2,
    products: 6,
    agents: 18,
  },
  keywords: [
    "ai integration for business",
    "ai consultant philippines",
    "ai automation services",
    "ai agent development",
    "custom ai solutions",
    "ai web app developer",
    "next.js ai developer",
    "full-stack ai builder",
    "hire ai developer",
    "ai for small business",
    "internal tools developer",
    "google sheets automation philippines",
    "apps script developer",
    "bookkeeping automation e-commerce",
    "shopify integration philippines",
    "pricing tool",
    "jay consejo",
  ],
  nav: [
    { label: "Work", href: "/#projects" },
    { label: "Process", href: "/#process" },
    { label: "About", href: "/#about" },
  ],
  ctaLabel: "Let's Talk",
  ctaHref: "/#contact",
  social: {
    linkedin: "https://www.linkedin.com/in/jayconsejo/",
    github: "https://github.com/jay-consejo",
  },
} as const;
